### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by 1luap** [ncase/trust#100]
I started to work on the Finnish translation today.

**Comment by 1luap** [comment]
The first version of the translation is now ready: https://1luap.github.io/trust

**Comment by ncase** [comment]
Awesome, thank you so much @1luap ! (and thanks for waiting!) Your translation is now linked to from the main page :)

![image](https://user-images.githubusercontent.com/825858/66520452-2c9e5700-eab7-11e9-80cc-a876ace1df22.png)
