### ISSUE TITLE
Tagalog translation started again

### ISSUE THREAD

**Issue by poypoyan** [ncase/trust#107]
Feel free to contact me if you want to help me. :)

**Comment by uzzielperez** [comment]
Hi @poypoyan, I would like to collaborate on a Tagalog translation! Interested to see what you have done so far!

**Comment by poypoyan** [comment]
@uzzielperez Sure, you may check and edit my translations if it is wrong. Note that some words are translated "slightly differently" from the orig because too long, while some words are left untranslated mid-sentence because I do not know how to translate it decently (yet). Thanks for helping!

**Comment by uzzielperez** [comment]
@poypoyan cool! Thanks for the invite! I will take a look in the weekend. Would love to see this in Tagalog soon.

**Comment by uzzielperez** [comment]
Hi @poypoyan, I made some changes in this [branch](https://github.com/uzzielperez/trust/tree/Tagalog)! Ang dami mo na pala nagawa! 🥇 

Would you like to host this somewhere? 

-------
Recipe for adding remote and pulling changes from a fork for future collaborators. Also, just so I won't forget.
```bash 
git remote add poypoyan git@github.com:poypoyan/trust.git
git fetch poypoyan/gh-pages
git fetch poypoyan
git pull poypoyan gh-pages
git add words.html 
git commit -m "Corrections and additional translations"
```

or 

```bash 
git remote add uzzielpereztrust git@github.com:poypoyan/trust.git
git fetch uzzielpereztrust/gh-pages # git fetch uzzielperez/Tagalog
git fetch uzzielpereztrust
git pull uzzielpereztrust gh-pages # or Tagalog branch
git add words.html 
git commit -m "Corrections and additional translations"
```

**Comment by poypoyan** [comment]
@uzzielperez Sure, you may host it somewhere, but I do not completely know what you will do (Sorry I do not know much about git). I think I would like more to contribute there than on my fork.

**Comment by uzzielperez** [comment]
@poypoyan So I just basically pulled the contents of your fork and pushed to my [Tagalog branch](https://github.com/uzzielperez/trust/tree/Tagalog). If you want to get my updates you can follow the second recipe above or just continue making changes in your fork and I will just copy them. Whichever is more convenient for you! 

I'll try to set up a website for this when we are done translating. :)

**Comment by poypoyan** [comment]
I'm dooone!

Note: My translation "style" is a bit formal, especially in grammar. In terms of nouns, adjectives, etc., Spanish and English loans are allowed, but native terms are "prioritized." Hence there are some Tagalog and Spanish words which I think are "good" translations, but not commonly encountered, like _pasumala_ (random), _utak-biya_ (idiomatic expression for stupid/simpleton), _trintsera_ (trench), _pulpol_ (dull, both about knifes and mind) and more. English idiomatic expressions, like "close, but no cigar" are left untranslated, except for the main one "live and let live."

Maybe anyone may still edit (esp. mistakes, words I missed), but I wish my "style" remains...

**Comment by poypoyan** [comment]
@uzzielperez kailan mo po maaaring gawin at ipadala ang translation? Thanks!

**Comment by uzzielperez** [comment]
hi @poypoyan, bibigyan ko ng panahon ngayong weekend! Tapos ko na halos yung translation. :D

**Comment by poypoyan** [comment]
hi @uzzielperez, since your pull request, may isa pa akong commit for finishing fixes. Thanks!

**Comment by uzzielperez** [comment]
Hi @poypoyan, sige. I'll pull the changes. :) Sorry di ko pa naupuan ulit. Hinihintay ko na lang bakasyon and then I'll work on it.

**Comment by uzzielperez** [comment]
Hi @poypoyan! Here's the temp link to the website: [Trust](https://humaninteraction.github.io/HumanInteraction/). 
I plan to change the name of the website to "Tiwala" instead of HumanInteraction. :) Anyway, Merry Christmas and Happy New year to you!

**Comment by poypoyan** [comment]
@uzzielperez Woah... woah😮... yeah I think "tiwala" is better. Sorry I made a little change just now. Pwede bang madagdag 'yung recent ko? Thank you, Merry Christmas, and Happy New year rin sa'yo!

**Comment by uzzielperez** [comment]
Hi @poypoyan! Eto na yung bagong page! :D Sige add ko yung recent mo. Pero ito na yung page [tiwalaPH](https://tiwalaph.github.io/TiwalaPH/)

**Comment by poypoyan** [comment]
@uzzielperez Thanks so much! Siguro kopyahin mo na lang yung words.html, kasi dun na lang naman ako nag-edit hahaha 😄 ~~Siguro pagkagising ko mamaya~~ saka ko ipadala sa email.

"Filipino (Tagalog)" ba 'yung ipalalagay sa README, tapos "Tagalog" naman 'yung ipalalagay sa baba?

**Comment by uzzielperez** [comment]
@poypoyan, sige! Try ko this weekend :)

**Comment by poypoyan** [comment]
@uzzielperez Kung marami po kayong ginagawa, paimbita na lang po ako ng akses sa TiwalaPH, para ako na lang ang mag-eedit. Thanks!

**Comment by uzzielperez** [comment]
@poypoyan , inininvite na kita! Pasensya na. medyo marami nga ginagawa. :) Let me know kung may problema.

**Comment by poypoyan** [comment]
@uzzielperez Thank you! Also, good luck sa mga ginagawa huhuhu...
