### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by Saul-BT** [ncase/trust#16]
Hello, I love this game, the idea is awesome, it is well crafted and very well thought out.
I would like to propose a translation into Spanish so that it reaches more people, and the translation could do it myself (I am from Spain).
My email is alu15067@iesgalileo.es

**Comment by ncase** [comment]
Thank you so much for the offer @Saul-BT! I recently pushed up the instructions for translating EvoTrust: https://github.com/ncase/trust#how-to-translate-this-thang

Also @jonathancross & others are working on a better translation system, maybe give that a try? See: https://github.com/ncase/trust/issues/5

**Comment by ccamara** [comment]
@Saul-BT , I have just read your post now. I have already started and submitted a Spanish version (sorry for not having told you before and apologies if you have been working in vane - I have just discovered that there are some people working on a better translation system, which I think would be needed). Feel free to send any comments or suggestions on the translated repo: http://github.com/ccamara/trust

**Comment by Saul-BT** [comment]
I realized
