### ISSUE TITLE
translation: gender

### ISSUE THREAD

**Issue by jkoelling** [ncase/trust#25]
@ncase Translating this awesome thing to German leads to a few additional gender related choices for the text. If I take some more liberty with the text I can get around most situations. I'm not yet sure if I'll always be able to do so without becoming too long for the available space. Being gender neutral in German is sadly a bit more complicated than in English. My current default, if I can not easily avoid gender, would be to go with the female version of the word. Any preferences from your side?

One specific thing: you used "they" for the labels of the payoff matrix. We don't really have a gender neutral pronoun (that I'm aware of, still asking around) that is not a new word or at least somewhat established.

**Comment by ncase** [comment]
Ah, good point, I hadn't thought about that!

> My current default, if I can not easily avoid gender, would be to go with the female version of the word. Any preferences from your side?

Sounds good to me! :)
