### ISSUE TITLE
Started a Bulgarian translation

### ISSUE THREAD

**Issue by zbrox** [ncase/trust#30]
Title says it all :)

**Comment by Hollowese** [comment]
Аз мога ли да помогна? :)

**Comment by zbrox** [comment]
@Hollowese Супер! Започнах точно преди един музикален фестивал така, че не съм превел много. :) https://github.com/zbrox/trust

**Comment by Hollowese** [comment]
Благодаря, заемам се!

2017-08-14 11:13 GMT+03:00 Rostislav <notifications@github.com>:

**Comment by zbrox** [comment]
@Hollowese прогрес? Предложения за разпределение на работата? Днес може би ще имам време привечер да продължа работа, та се притеснявам да не повтарям вече свършена работа без да искам.

**Comment by zloster** [comment]
До всички заинтересувани. Вече има "официален" превод на български. Намира се тук: https://github.com/ncase/trust-bg
@ncase This issue could be closed because now there is an official Bulgarian translation.
