### ISSUE TITLE
Ukrainian translation started

### ISSUE THREAD

**Issue by Yaroslav-F** [ncase/trust#31]
...not sure when it will be finished though. Dealing with cyrillic alphabet can be fun!

**Comment by gooduling** [comment]
Russian cyrillic translation with TimesNewRomans font looks ugly. We definitely should use some custom font.
https://likzet.github.io/trust/

**Comment by Yaroslav-F** [comment]
@gooduling this font might work: https://ayuprogrammers.github.io/trust/ . I'll find something that looks more or less hand-written :)

**Comment by gooduling** [comment]
Ne pogano! :)

**Comment by gooduling** [comment]
How it goes, man? I can help to translate some part during this weekend. Say, I can translate Intro and first 300 lines of code in words.html

**Comment by Yaroslav-F** [comment]
All good here. I'm currently on line 368 of words.html and line 77 of notes/index.html . Not much more left. I might ask you to review my translation when I'll finish if that's okay?
Anyway, I'll push my progress to my fork and will keep going, feel free to create pull requests to it :)

**Comment by gooduling** [comment]
Sure. Just let me know when you'll finish

**Comment by gooduling** [comment]
Good job! Quite high quality of translation.

**Comment by Yaroslav-F** [comment]
Thanks :)
You can finish notes/index.html for me if you like (and have spare time ofc). I'll get to that after finishing with words.html (line 510 now!) otherwise.

**Comment by Nick-IronTower** [comment]
Як просувається справа? Треба підмога?

**Comment by wombat86** [comment]
@Yaroslav-F, what about creating separate issues for different parts of translation so that few could work on the translation in parallel? I also can help btw.

**Comment by Yaroslav-F** [comment]
@Nick-IronTower Просуваюся крок за кроком. Намагатимусь закруглитися до 30го числа, перед відпусткою. Відпишуся про прогрес 29го :)
@wombat86 you're very welcome to create Issues/PRs to my fork, any help is appreciated! Especially with notes/index.html file.

**Comment by RusevPaul** [comment]
@Yaroslav-F Якщо потрібна допомога з перекладом, маю команду, яка допоможе. По закінченню можу продивитись по тексту для більшої ефективності ;)

**Comment by ghost** [comment]
@Yaroslav-F Теж допоможу, якщо потрібно. Почала свій, аж потім додивилась, шо вже в процесі)

**Comment by ghost** [comment]
@Yaroslav-F щодо шрифтів - недавно шукала безкоштовні рукописні, то деякі приміряла на головну і текстову сторінки гри, пдфку з 8 прикладами можна подивитись тут: https://drive.google.com/file/d/0Bzoou1o9QYmVdmxxT2EyY0hKYzA/view?usp=sharing
Є як мінімум 2 норм: Noteworthy i Chalkboard SE.

**Comment by Yaroslav-F** [comment]
@irnerne Чудова робота, Jacob CTT виглядає просто розкішно! Якщо ніхто в цій гілці не проти, Jacob CTT буде нашим шрифтом ^_^
@RusevPaul @irnerne @wombat86 @Nick-IronTower @gooduling Підмога і справді знадобиться. Я йду в відпустку на 2 тижні та намагатимусь триматися якнайдалі від комп'ютера.

На даний момент _words.html_ перекладений **до 719го рядка (з 1223)**, _notes/index.html_ - до **72го (з 112**). Решта файлів перекладені повністю. Якщо будь-хто захоче перевірити чи продовжити існуючий переклад - буду дуже-дуже вдячним. Якщо ні - доведеться чекати ще 2 тижні ⏳  .
В будь-якому випадку, Pull requests & Issues вітаються тут https://github.com/Yaroslav-F/trust .

**Comment by Yaroslav-F** [comment]
Translation finished: https://github.com/Yaroslav-F/trust 🎉 🎉 

Got some tiny CSS issues here and there, so asked @ncase whether I can just go ahead and fix them or if they want to do it themselves to ensure I don't break anything 🦀 .
Will keep this branch posted, thanks for your patience everyone!

PS: As always, if anyone wants to read through the translation to improve it - you're most welcome to do so!

**Comment by jkoelling** [comment]
I modified a couple of things for the German translation and @ncase didn't mind. I'm sure they'll be happy if you do and test it yourself. And if they really want to have their own look at it, it's easier to review the fixed version than to do the fixes. :)

**Comment by Yaroslav-F** [comment]
yup, just got a blessing so going to do couple of changes to css 🙂

**Comment by Yaroslav-F** [comment]
It is done!
![screenshot 18](https://user-images.githubusercontent.com/4863615/31165216-2055bda8-a8e2-11e7-8b8d-90e906710182.png)
