### ISSUE TITLE
Translation to Czech

### ISSUE THREAD

**Issue by Martin819** [ncase/trust#32]
Started to translate.

**Comment by omichalek** [comment]
spojme síly // we can join our forces, I have a beginning translated already at
https://github.com/omichalek/duvera/

I am aiming at 
- informal addressing of the player (tykání) - I usually do not like this, but I feel that using the formal addressing would feel alien to children - one of the target groups
- gender neutral language

...
yes, our language is complicated

Also, the used font lacks Czech letters, suggested replacements are welcome!

**Comment by hovi** [comment]
Hey,
what's status of this one? Might be able to help!

**Comment by nextghost** [comment]
Since the only Czech translation in progress has been stuck half-finished for a while and contains some serious mistakes in basic terminology, I'm starting from scratch [here](https://github.com/nextghost/trust).

**Comment by nadvornix** [comment]
Hi! @nextghost 
What is state of your translation? Is it finished and published? If not I can do it, if you want.

**Comment by nextghost** [comment]
@nadvornix The game is completely translated but I haven't had time to finish translating the extra notes. I'll get to it sometime in April.

**Comment by nadvornix** [comment]
Great, thanks. In case you would want help don't worry to ask me.

**Comment by nadvornix** [comment]
@nextghost Hi, how it's going?

**Comment by nextghost** [comment]
@nadvornix Still working on it, check back in the weekend.

**Comment by nadvornix** [comment]
Thanks!

**Comment by ncase** [comment]
Thank you all! It's been pulled :) https://github.com/ncase/trust/pull/97
