### ISSUE TITLE
Translation to polish

### ISSUE THREAD

**Issue by paddyzab** [ncase/trust#35]
Will try to finish it till the end of weekend.

Contributors welcomed on the fork, cheers.

**Comment by sin** [comment]
Hi, I already translated it into polish: https://github.com/sin/trust & https://sin.github.io/trust/

@agagata also started translating it into polish here: https://github.com/agagata/trust

We're going to merge our translations eventually. @agagata's friend agreed to proofread it and she's a professional translator, so it's going to be awesome :) 

CC @KrzysztofMadejski

**Comment by ncase** [comment]
Thank you so much, @sin! (Sorry for the late reply, was visiting family last week) I've pushed your translation up to the main site: 

![image](https://user-images.githubusercontent.com/825858/29428915-da6dce52-835c-11e7-9e66-4831d2ddcbe6.png)

Many thanks again! :)

**Comment by JoannaFalkowska** [comment]
Polish has gendered verb conjugation. It really throws me off as a woman because the default chosen for this translation is male. Would you accept a fork that adds gender choice at the beginning, if done right and pretty of course? Polish version also has minor styling issues that I'd be glad to fix (if that's possible for only one language version, I'm not sure).

**Comment by agatku** [comment]
@Senthe we're aware of the things you mentioned and we're working on them in this issue https://github.com/agagata/trust/pull/1 We'll merge it soon [hopefully today-tomorrow] so maybe then you could take a look? We'd appreciate your help :)

**Comment by JoannaFalkowska** [comment]
@agagata Thanks for the response, I'm glad you're working on this : ). If I have the time, I'll take a look this weekend.

**Comment by DavidSypniewski** [comment]
Polish letters do not work correctly with this font (look at the "Ł")
![image](https://user-images.githubusercontent.com/31244815/29565516-92080d4c-8746-11e7-8b8d-c788c46b2b97.png)

**Comment by DavidSypniewski** [comment]
![image](https://user-images.githubusercontent.com/31244815/29565570-c4788db0-8746-11e7-93e7-5d90d2439d3a.png)
At the end of the single game the text hides under the buttons

**Comment by sin** [comment]
@DavidSypniewski I just changed the font to one that supports polish letters and we're working on other issues right now. As @agagata said, we would appreciate your help if you could take a look again tomorrow. :)

**Comment by DavidSypniewski** [comment]
@sin the font is fine!

**Comment by paddyzab** [comment]
Closing this issue.
Thanks @sin.

For the future, follow the protocol described by @ncase to make it clearer to other people that you started working on it.
Saves time for all people around.

**Comment by KrzysztofMadejski** [comment]
Sorry @paddyzab for the confusion, when @agagata @sin started translation there was only one [general issue](https://github.com/ncase/trust/issues/5) and no recommended protocol.
