### ISSUE TITLE
Translation to Korean

### ISSUE THREAD

**Issue by osori** [ncase/trust#37]
I'm translating this game into Korean. Let me know if anyone is interested in collaborating!

**Comment by kylecho** [comment]
I'm down. How much have you translated?

**Comment by kylecho** [comment]
I'm down. I will fork your repo and contribute to it.

**Comment by osori** [comment]
Great! I just merged your pull request on Noise section. 

I'll be focusing on translating from the back since you might be translating Sandbox right now as it's the section right after what you just translated, so that our translations do not overlap.

**Comment by osori** [comment]
Korean translation is done :)
