### ISSUE TITLE
Persian فارسی translation

### ISSUE THREAD

**Issue by hamed** [ncase/trust#42]
I have translated it to Persian, I also made some quick fix for the right to left scripts.
https://github.com/hamed/trust

**Comment by MudarAljundi** [comment]
That would be great! There are a few areas where your repo helps mine! I'd also like to share some hacks that will change the numerals to Arabic in the thumbnail and the scripts, like so:

![asdf2](https://user-images.githubusercontent.com/13874863/29427541-22e4bf74-8358-11e7-88b6-0e045dfae472.png)

Is it fine if I open an issue on your GitHub repo?

**Comment by hamed** [comment]
That would be great!

**Comment by MudarAljundi** [comment]
One quicky problem. I can't find the "Issues" tab... 😅
![asdf3](https://user-images.githubusercontent.com/13874863/29428092-f272564c-8359-11e7-81d6-cc68f2c82410.png)

**Comment by hamed** [comment]
solved!

**Comment by ncase** [comment]
Thank you @hamed & @MudarAljundi! I've pushed the Persian/Farsi version up to the main page!

![image](https://user-images.githubusercontent.com/825858/29431202-23384f56-8365-11e7-8b8e-5d692067ef86.png)

(Also, um, because I am not a very worldly-cultured person... what's the difference between Persian & Farsi?)

**Comment by hamed** [comment]
Wonderful!
Others call it Persian, we call it Farsi.

**Comment by ncase** [comment]
Ah, thanks @hamed! :)

Also I forgot to mention last time, but _wow_ I'm super impressed with how you + @MudarAljundi managed to right-to-left flip EVERYTHING, even the scoreboard & bottom navigation bar.

Many thanks again! I'll close this issue now~

**Comment by hamed** [comment]
Thank you for this masterpiece!
