### ISSUE TITLE
My Application

### ISSUE THREAD

**Issue by YunTp** [ncase/trust#59]
Can I use the ideas of your work to create a free little software? Non-profit. Please.

Thank you for your reading . Best wishes to you .

**Comment by YunTp** [comment]
Please . Can I ... ?

**Comment by ncase** [comment]
Yeah of course! All my work is public domain, Creative Commons Zero: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by YunTp** [comment]
Thank you . When I finish it , I will upload it to my github.
