### ISSUE TITLE
Chapter 5, number of rounds slider not functional

### ISSUE THREAD

**Issue by dr4Ke** [ncase/trust#73]
In the beginning of the fifth chapter, there is a slider to choose the number of rounds to play.
Whatever the value is, the game plays indefinitely. Shouldn't it stop at the set number of rounds?

Tried with Firefox 59 and Chrome 59.

Great soft, by the way!

**Comment by zommuter** [comment]
That's working as intended. The slider only modifies the amount of rounds _per_ tournament, but the game will still play (and evolve) tournaments indefinitely.

**Comment by dr4Ke** [comment]
OK. I just didn't understand the meaning of it. Thanks for clarifying.
